apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://kubeflow.github.io/spark-operator'
      targetRevision: 2.3.0
      chart: spark-operator
      helm:
        # Mengambil custom values dari repositori Git Anda sendiri
        valueFiles:
          - $values/infrastructure/spark-operator/values.yaml
    - repoURL: 'https://github.com/Alvarras/airflow-spark-k8s-gitops.git'
      targetRevision: main
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: spark-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true